name: Update resume PDFs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Update resume PDFs
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Compile LaTeX for all PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make all
      - name: Delete placeholder release
        uses: actions/github-script@v6
        continue-on-error: true # in case there's no existing release
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            const { data: { id } } = await github.rest.repos.getLatestRelease({ owner, repo })
            await github.rest.repos.deleteRelease({ owner, repo, release_id: id })
      - name: Delete release tag
        run: |
          git tag -d release
          git push origin :release
        continue-on-error: true # in case there's no existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Placeholder release for the latest build of my resume."
          name: Latest
          tag_name: release
          draft: false
          prerelease: false
          files: |
            resume.pdf
            full.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
